// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Peacock.Dal;

namespace Peacock.Dal.Migrations
{
    [DbContext(typeof(PeacockDbContext))]
    [Migration("20190714035559_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Peacock.Dal.T_System_LanguageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("DisplayContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LanguageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("LastUpdatedTime")
                        .HasColumnType("datetime");

                    b.Property<int>("RelationId");

                    b.HasKey("Id");

                    b.HasIndex("RelationId");

                    b.ToTable("T_System_LanguageContent");
                });

            modelBuilder.Entity("Peacock.Dal.T_System_LanguageRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("T_System_LanguageRelation");
                });

            modelBuilder.Entity("Peacock.Dal.T_System_Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("LanguageRelationId");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("ParentId");

                    b.Property<int>("Seq");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("LanguageRelationId");

                    b.ToTable("T_System_Menu");
                });

            modelBuilder.Entity("Peacock.Dal.T_System_LanguageContent", b =>
                {
                    b.HasOne("Peacock.Dal.T_System_LanguageRelation", "Relation")
                        .WithMany("TSystemLanguageContent")
                        .HasForeignKey("RelationId")
                        .HasConstraintName("FK_T_System_LanguageContent_T_System_LanguageRelation");
                });

            modelBuilder.Entity("Peacock.Dal.T_System_Menu", b =>
                {
                    b.HasOne("Peacock.Dal.T_System_LanguageRelation", "LanguageRelation")
                        .WithMany("TSystemMenu")
                        .HasForeignKey("LanguageRelationId")
                        .HasConstraintName("FK_T_System_Menu_T_System_LanguageRelation");
                });
#pragma warning restore 612, 618
        }
    }
}
